---
language: node_js
node_js:
  - "4"

sudo: false

cache:
  directories:
    - node_modules

env:
  - EMBER_TRY_SCENARIO=default
  - EMBER_TRY_SCENARIO=ember-1.13
  - EMBER_TRY_SCENARIO=ember-release
  - EMBER_TRY_SCENARIO=ember-beta
  - EMBER_TRY_SCENARIO=ember-canary

matrix:
  fast_finish: true
  allow_failures:
    - env: EMBER_TRY_SCENARIO=ember-canary

before_install:
  - npm config set spin false
  - npm install -g bower
  - bower --version
  - npm install phantomjs-prebuilt
  - phantomjs --version

install:
  - npm install
  - bower install

script:
  # Usually, it's ok to finish the test scenario without reverting
  #  to the addon's original dependency state, skipping "cleanup".
  - ember try:one $EMBER_TRY_SCENARIO test --skip-cleanup

notifications:
  email: false
  slack:
    secure: "EogQWjtzYPRjunFUJZHeHoEcrCCX17IEF3pJgI8CV2UxDd+n3Qrv58SgjjPJx91LuEQ8yjcYOOilLSvVLikCPJ5iqO/6VDWKppR1K9PitiO3X0yHKb2+53lhiN/5er1HMptEZ46P+jzKFLBhheEy0kUX+gPZV3bn2EES2a9AP+P3n9YEoDc+tg+Yv/ieSW8ld33LOvKbA+ZJXATtPlaAps0dbWEs4sJqP80AAkuXBP+4OU089h2V96vrqfBnQkQcH04Z5PAFXPi+3F2urTz+o5ZQ0FjHyBtcWdlmvERHQmP9+RHtffYGvhgDCps0eqZkvgQdX0moSfjQroA5Y1vEzrqdrp5DkecmawygtBmRlkRoS//c42Ztj9uEfPeKcfdvYjF5p/XcLrJC1GZkuTpWldyUb+RwKw1VM0P6pNjydm0kTmJzYMea164IuQU1r8r2e9Z0Sen50bG7Zf3t2tXsp+4IZVfDRrKgLFH2Uveoe8bUNRd8EDvSAxD9f9Iq0N7Z+WXny7XCa6Uux+TmMoC/Ut8JZ8rJnhWq30DkrdrpoeRDVGn3/5Qgc4Sn+uetfkIb2e+gPzxP8bYqQif+l9U4edM0CY2fgaNkk7iFBTDMb4wKyjlD9G7bbyf7RvC+87sMq2AX/tKlSceLXFig/AEJXVjeYBbKBbtsSxvvlFPdCE0="
