---
language: node_js
node_js:
  # we recommend testing addons with the same minimum supported node version as Ember CLI
  # so that your addon works for all apps
  - "6"

sudo: false
dist: trusty

addons:
  chrome: stable

cache:
  directories:
    - $HOME/.npm

env:
  global:
    # See https://git.io/vdao3 for details.
    - JOBS=1

branches:
  only:
    - master
    # npm version tags
    - /^v\d+\.\d+\.\d+/

jobs:
  fail_fast: true
  allow_failures:
    - env: EMBER_TRY_SCENARIO=ember-canary

  include:
    # runs linting and tests with current locked deps

    - stage: "Tests"
      name: "Tests"
      script:
        - npm run lint:hbs
        - npm run lint:js
        - npm test

    # we recommend new addons test the current and previous LTS
    # as well as latest stable release (bonus points to beta/canary)
    - stage: "Additional Tests"
      env: EMBER_TRY_SCENARIO=ember-lts-2.18
    - env: EMBER_TRY_SCENARIO=ember-lts-3.4
    - env: EMBER_TRY_SCENARIO=ember-release
    - env: EMBER_TRY_SCENARIO=ember-beta
    - env: EMBER_TRY_SCENARIO=ember-canary
    - env: EMBER_TRY_SCENARIO=ember-default-with-jquery

before_install:
  - npm config set spin false
  - npm install -g npm@4
  - npm --version

script:
  - node_modules/.bin/ember try:one $EMBER_TRY_SCENARIO

notifications:
  email: false
  slack:
    secure: "EogQWjtzYPRjunFUJZHeHoEcrCCX17IEF3pJgI8CV2UxDd+n3Qrv58SgjjPJx91LuEQ8yjcYOOilLSvVLikCPJ5iqO/6VDWKppR1K9PitiO3X0yHKb2+53lhiN/5er1HMptEZ46P+jzKFLBhheEy0kUX+gPZV3bn2EES2a9AP+P3n9YEoDc+tg+Yv/ieSW8ld33LOvKbA+ZJXATtPlaAps0dbWEs4sJqP80AAkuXBP+4OU089h2V96vrqfBnQkQcH04Z5PAFXPi+3F2urTz+o5ZQ0FjHyBtcWdlmvERHQmP9+RHtffYGvhgDCps0eqZkvgQdX0moSfjQroA5Y1vEzrqdrp5DkecmawygtBmRlkRoS//c42Ztj9uEfPeKcfdvYjF5p/XcLrJC1GZkuTpWldyUb+RwKw1VM0P6pNjydm0kTmJzYMea164IuQU1r8r2e9Z0Sen50bG7Zf3t2tXsp+4IZVfDRrKgLFH2Uveoe8bUNRd8EDvSAxD9f9Iq0N7Z+WXny7XCa6Uux+TmMoC/Ut8JZ8rJnhWq30DkrdrpoeRDVGn3/5Qgc4Sn+uetfkIb2e+gPzxP8bYqQif+l9U4edM0CY2fgaNkk7iFBTDMb4wKyjlD9G7bbyf7RvC+87sMq2AX/tKlSceLXFig/AEJXVjeYBbKBbtsSxvvlFPdCE0="

deploy:
  provider: npm
  email: me@tomasbasham.co.uk
  api_key:
    secure: "VeHlO8UfgCR71qvzCD/y9+woaYVWJiu3mRwKte++CsnQHl2TjYz/nB7AzyTto4gFExOhlmmgzhsJNQh7TM2v3h3BYqDhtc45lpGEo5JdPhrDxGvXxFpob8bwcNL5np5PWBvQVr66k/3q4L5Abp1y13q7ukyTJw0WpDxms4RXC0D/120aOIzZMb2eT0eg7I+EMjuImHVLSECCKKdTJOyaHNLY4ivhMp8lDtLqXl7ue7czCm1Hinqcn4/MsrLoK7z3Qie7GdZ/uuS8oNo9WUvWgR8uxnmPRYd8SqDh3ZxR++jYNRxqg7BlVsT5xHTd5OvebDaIF+hVln1og+JBr2fIZ40lxXKhK0PBSWRXzPsqacO8Rb+j9bVDp1sV/SiNunNeesWhGUQQqN2k5iIodQPox/LdTk1EpoijtrGLfA4MhmmMKkEPPgrtFaldwVfxrkBuywA6zvIMCNmze1MtiTgMhcx/VRq144jmpowLeVNkyCgrbXFAzf13qoaRUM9lSIi+FtkzsbFsfJdr5joegE47txBjkNTwDa5CrUAV03lMQA670hWAE+J8KBoGpijeP49MqgX8yCmXpg+NwSf9TRIn9n6xK8NEq6C8FV5/DefshW1GmF+zg/2uP+MBVT9I+Fzwq7gqAQke180Z77AkKow0iBm1oh44hdl5lTSi2tfT97s="
  on:
    tags: true
    repo: tomasbasham/ember-cli-pubnub
